name: lint, test and build actions

on:
  push:
    branches: [main, Add-github-actions-workflows]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Get repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies & run lint
      run: |
        npm ci
        npm run lint
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dest-files
        path: ./

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Get repository
      uses: actions/checkout@v2
    - name: Get Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: dest-files
    - name: list contents
      run: ls
    - name: Deploy
      run: echo "deploying...."





