name: lint, test and build actions

on:
  push:
    branches: [main, add_cache_outputs_to_jobs]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Get repository
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Cache dependencies
      id: cache-npm
      uses: actions/cache@v3
      env:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Test code
      run: npm run test


  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.output01 }}
    steps:

    - name: Get repository
      uses: actions/checkout@v3
    - name: Cache dependencies
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    - name: Publish JS filename
      id: publish
      run: find artifacts/*.txt -type f -execdir echo 'output01={}' >> $GITHUB_OUTPUT ';'
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dest-files
        path: artifacts

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Get repository
      uses: actions/checkout@v3
    - name: Get Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: dest-files
    - name: list contents
      run: ls
    - name: Output filename
      run: echo "${{ needs.build.outputs.script-file }}"
    - name: Deploy
      run: echo "deploying..."





