name: Handle Issues

on:
  issues:
    types: [opened]


jobs:
  info:
    runs-on: ubuntu-latest

    steps:
    - name: Output Github Actions Outputs
      run: |
        echo "${{ toJSON(github.event) }}"
