name: lint, test and build actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Get repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: |
        npm install eslint-plugin-react@latest
        npm init @eslint/config
        npx eslint .

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Get repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build


